import { DatabaseSync } from 'node:sqlite'
import { existsSync, mkdirSync, readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * The records, as a file on the classroom laptop (ADR-0035).
 *
 * `Documents\TechTech Flight\records.db`, holding the eighteen tables of `db/schema.sql`.
 * `node:sqlite` is built into Node 24, so there is no dependency, no install and no server: a
 * technician handed a trolley never sees any of it.
 *
 * **In Documents, not in the app folder, and that is load-bearing.** An update is a replaced
 * folder, so anything inside the app folder is destroyed by one. A term of attendance must not
 * depend on somebody remembering to copy it out first.
 *
 * **No live readings, ever.** No altitude, no battery, no position. This holds what happened,
 * never what is happening. Coordinates appear on `zone_point` and `checkpoint` only, because
 * those are what a Teacher set rather than what an airframe reported.
 *
 * **Written at Lesson boundaries, never per telemetry tick.** A file written twice a second by
 * a classroom of drones is being used as a log, and this is a record.
 */

/** Where the schema lives, so the file and `db/schema.sql` cannot drift apart. */
function schemaPath(fromDir = dirname(fileURLToPath(import.meta.url))): string {
  return resolve(fromDir, '..', '..', 'db', 'schema.sql')
}

/**
 * The folder a school already knows about.
 *
 * `Documents` on Windows and the home folder elsewhere, because this is aimed at a Windows
 * trolley laptop and a developer on anything else should not have a `Documents` invented for
 * them.
 */
export function recordsPath(home = homedir()): string {
  const documents = process.platform === 'win32' ? join(home, 'Documents') : home
  return join(documents, 'TechTech Flight', 'records.db')
}

/**
 * The statements SQLite will accept from `db/schema.sql`.
 *
 * The file is written for Postgres, which is what the off-site copy would be. Three things do
 * not carry, and each is a translation rather than a change of shape:
 *
 *  - `uuid` becomes `text`. SQLite has no uuid type and the ids are generated by the caller.
 *  - `gen_random_uuid()` goes; the caller supplies ids, which it has to anyway to match the
 *    browser's own records.
 *  - `timestamptz` becomes `text`, holding an ISO instant, which is what a record is read as.
 *
 * Translated here rather than by keeping a second schema file, because two schemas drift and
 * the eighteen tables are the thing both ends have to agree on.
 */
export function sqliteSchema(postgres: string): string {
  return postgres
    .replace(/\bbegin;|\bcommit;/g, '')
    .replace(/\s+default gen_random_uuid\(\)/g, '')
    .replace(/\buuid\b/g, 'text')
    .replace(/\btimestamptz\b/g, 'text')
    .replace(/\bnumeric\b/g, 'real')
    .replace(/\bboolean\b/g, 'integer')
    .replace(/\bint\b/g, 'integer')
}

export interface RecordsDb {
  readonly db: DatabaseSync
  readonly path: string
  close(): void
}

/**
 * Open the records file, creating the folder and the tables the first time.
 *
 * Idempotent: every statement is `create table if not exists`, so a laptop that has run a
 * hundred lessons and one that has never been opened take the same path. First run must not
 * fail differently on a machine that has never seen this.
 */
export function openRecords(path = recordsPath()): RecordsDb {
  mkdirSync(dirname(path), { recursive: true })
  const db = new DatabaseSync(path)

  /*
   * Write-ahead logging, so a reader never blocks the write that a Teacher is waiting on and a
   * crash leaves the file readable rather than half-applied.
   */
  db.exec('pragma journal_mode = wal')
  db.exec('pragma foreign_keys = on')

  const source = schemaPath()
  if (existsSync(source)) db.exec(sqliteSchema(readFileSync(source, 'utf8')))

  return { db, path, close: () => db.close() }
}

/** Every table the file holds, for a check that the schema actually arrived. */
export function tableNames(db: DatabaseSync): readonly string[] {
  const rows = db
    .prepare("select name from sqlite_master where type = 'table' and name not like 'sqlite_%'")
    .all() as { name: string }[]
  return rows.map((row) => row.name).sort()
}
